name: Build & Push app image

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/build_and_push.yaml"
  workflow_dispatch:

env:
  REGION: us-central1
  REPO_ID: fastapi-app-repo
  IMAGE_NAME: fastapi-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth via Workload Identity Federation
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure gcloud project
        run: gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev" --quiet

      - name: Build & push image (app/)
        id: meta
        run: |
          IMAGE_HOST="${{ env.REGION }}-docker.pkg.dev"
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          IMAGE="${IMAGE_HOST}/${PROJECT_ID}/${{ env.REPO_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE" ./app
          docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Upload image-ref artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-ref
          path: image.txt
          retention-days: 1